Feature -> Endpoint that retrieves all channels
Programadores-Dominicanos/100-days-of-code-bot-server pull request #11
Opened 2024-10-26 22:08 UTC by ManasesLovera

Endpoint that retrieves all channels was created based on the discord-proxy module, let me know if anything should be modified or fixed.

### Created: 
1. channel.services
2. channel.controller

### Modified:
1. channel.module

### Deleted:
1. dto/
2. schemas/

> Based on discord-proxy.services

2024-10-26 22:29 UTC, stealkiller06 requested changes
Remember what we talked.
Channel is part of the discord feature, that's why channel needs to be inside discord-proxy

2024-10-26 22:38 UTC, ManasesLovera commented
Please review now

2024-10-26 22:43 UTC, stealkiller06 requested changes

2024-10-26 22:43 UTC, stealkiller06 commented on src/app.module.ts
> +    ChannelModule,
We don't need to import ChannelModule in app.module
Channel module is part of DiscordModule, so you just need to import it in DiscordModule and that's it 
See the example that we have in the ChallengeTrackerModule.

2024-10-26 22:52 UTC, ManasesLovera commented
Done!

2024-10-27 17:44 UTC, stealkiller06 approved these changes
LGTM

2024-10-27 17:44 UTC, merged